version: 0.2

env:
  variables:
    AWS_REGION: "eu-west-1"
    EC2_INSTANCE_ID: "i-08c0dd6469825af4a"
    S3_BUCKET: "lostfound-artifacts-bucket"
    ARTIFACT_PATH: "backend-build"

phases:
  install:
    commands:
      - export DEBIAN_FRONTEND=noninteractive
      - apt-get update -y
      - apt-get install -y jq wget unzip python3-pip awscli gnupg apt-transport-https lsb-release
      - pip3 install --no-cache-dir semgrep
      - wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor -o /usr/share/keyrings/trivy.gpg
      - echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/trivy.list
      - apt-get update -y
      - apt-get install -y trivy

  pre_build:
    commands:
      - semgrep --config=auto --json > semgrep-report.json || true
      - trivy fs --severity CRITICAL --no-progress --exit-code 1 .

  build:
    commands:
      - mvn clean verify
      - LATEST_JAR=$(ls target/*.jar | head -n 1)
      - aws s3 cp "$LATEST_JAR" "s3://$S3_BUCKET/$ARTIFACT_PATH/"

  post_build:
    commands:
      - echo "Deploying to EC2 instance..."
      - aws ssm send-command --instance-ids "$EC2_INSTANCE_ID" --document-name "AWS-RunShellScript" --parameters "commands=[\"aws s3 cp s3://$S3_BUCKET/$ARTIFACT_PATH/$(aws s3 ls s3://$S3_BUCKET/$ARTIFACT_PATH/ | sort | tail -n1 | awk '{print $4}') /home/ec2-user/app/app.jar\",\"sudo systemctl set-environment JAVA_TOOL_OPTIONS='--add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED'\",\"sudo systemctl daemon-reload\",\"sudo systemctl restart lostfound\"]" --region "$AWS_REGION"

artifacts:
  files:
    - target/*.jar
    - semgrep-report.json
  discard-paths: yes
